// =============================================================
// src/main.jsx
// Purpose: Vite entry point. Mounts the React app into the
//          #root div in index.html. Do NOT edit this file.
// =============================================================

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.jsx";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>
);
